# Run python app with MongoDB using Docker Compose
version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: swoosh_mongo
    expose:
      - "27017"
    volume:
      - mongo_data:/data/db

  app:
    build: ./src
    container_name: swoosh_app
    expose:
      - "8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/swoosh_db
    volumes:
      - ./logs:/app/logs
